"""Derive a tool's ADVERTISED parameter shape from the SDK request DTO.

The problem this removes
------------------------
An MCP tool's advertised ``inputSchema`` is generated by FastMCP from the Python
signature -- there is no separate declaration and no override hook. So the shape buyers
see has always been hand-written, and nothing tied it to the request DTO the SDK ships.
The two drifted freely: ``get_adcp_capabilities`` advertised ``protocols: list[str]``
where the DTO declares a typed enum, and ``ext: dict`` where the DTO declares
``ExtensionObject``. A buyer reading our schema and a buyer reading the spec saw
different contracts, and nothing failed.

The rule
--------
**Announced = the parameters the tool actually accepts; the DTO supplies the type of
every field it declares.** Both halves matter:

* A DTO field the tool does NOT accept is NOT announced. We never advertise a parameter
  the implementation would ignore, and there is no hand-maintained list of "unimplemented"
  fields to fall out of date -- absence from the signature IS the statement. To expose a
  new spec field you make the tool accept it, and the announcement follows automatically.
* A parameter the DTO DOES declare takes the DTO's type. This is the half that cannot
  drift: bump the SDK and every advertised type moves with it.

A third property was missing for a long time, and it is the one this module used to get
wrong: **the DTO supplies the TYPE, the library supplies the FIELD SET.** "Announced ==
accepted" said nothing about "announced == SPEC", and because the shape derives from OUR
subclass, a field added locally was published to buyers as though the spec defined it.
``list_accounts.idempotency_key`` was that field: account/list-accounts-request.json declares
no such property, the duty it was added for is TOLERANCE (that schema also declares
``additionalProperties: true``), and declaring it turned a tolerance obligation into an
invented spec field on MCP and REST. It has been removed.
It has been removed. A field we genuinely need is either ``exclude=True`` (internal, never
announced) or DECLARED ON THE SUBCLASS, which is itself the statement that we carry it: the
field is typed and greppable in the file the reader is already looking at, and the set is
derivable exactly as ``set(model.model_fields) - library_declared_fields(model)``. There is
no second list to keep, and no citation ClassVar -- see docs/development/building-tools.md.

A parameter the DTO does not declare is DROPPED from the announcement -- that is what
retires a legacy flat name such as ``list_creatives(status=...)``: FastMCP never passes what
it does not advertise, so there is no list of retired names to maintain. (This paragraph
used to say such a parameter "is still announced"; it never did, and a reader debugging why
a flat name stopped working was sent the wrong way by it.) Our advertised shape is therefore
always a SUBSET of the DTO, in exactly the DTO's form.

Transport independence
----------------------
This governs the ADVERTISED shape, which only MCP publishes. It deliberately does not
touch behaviour: A2A and REST reach the same ``_impl`` through the same request seam, so
the accepted field set and its meaning are identical everywhere and only the envelope
differs. Nothing here may become a per-transport branch.
"""

from __future__ import annotations

import inspect
from typing import Any

from pydantic import BaseModel

#: Names a builder. The tool -> DTO edge is read from the ARTIFACT -- the builder the
#: wrapper actually references in its BYTECODE, and that builder's return annotation --
#: never from the tool's NAME. Name-joining would be fooled by the real cases:
#: ``_build_update_request`` returns ``UpdateMediaBuyRequest``. Reading ``co_names``
#: rather than source text also keeps this out of reach of the source-scanning ban
#: (a bytecode reference is the call itself, not a string that resembles one).

#: Names a step in a tool's DISPATCH chain: the ``*_raw`` pass-through a wrapper may hop
#: through, and the ``*_impl`` the chain terminates at. Same artifact-not-name rule as
#: :data:`_BUILDER_NAME` -- ``get_media_buy_delivery`` reaches
#: ``_get_media_buy_delivery_impl`` only via ``get_media_buy_delivery_raw``, and no name
#: join could know that.


#: Contributed by version-envelope.json to every SDK request model. An ancestor that carries
#: only these grounds nothing -- it supplies no vocabulary for a DTO to be checked against.
_ENVELOPE_ONLY = frozenset({"adcp_version", "adcp_major_version"})


def sdk_grounding(model: type[BaseModel]) -> type[BaseModel] | None:
    """The SDK request model ``model`` inherits its vocabulary from, or None.

    "Announced = DTO fields INTERSECT the signature" only says something when the DTO comes
    from somewhere ELSE. A DTO hand-authored from the wrapper's own signature satisfies the
    intersection by construction: it declares what the wrapper declares, the derivation
    reproduces the hand-written shape, and the tool advertises whatever we happened to write
    while every test stays green. The DTO has to be the SPEC's vocabulary for the
    intersection to grade anything.

    Grounding is decided by walking the live MRO and asking where a field-carrying ancestor
    is DEFINED, so it consults no import spelling and has no spelling to miss.
    ``adcp.types.base.AdCPBaseModel`` and ``AdcpVersionEnvelope`` do not count: inheriting a
    base class with no request fields, or with the version envelope alone, leaves every
    buyer-facing field hand-written.
    """
    for ancestor in model.__mro__:
        module = ancestor.__module__
        if module != "adcp" and not module.startswith("adcp."):
            continue
        if set(getattr(ancestor, "model_fields", {})) - _ENVELOPE_ONLY:
            return ancestor
    return None


def apply_signature(fn: Any, signature: inspect.Signature) -> None:
    """Give ``fn`` an advertised signature.

    A one-line helper because the parameter is typed ``Any``: a function object has no
    declared ``__signature__``, so writing it directly is an ``attr-defined`` error and every
    caller paid a type-checker suppression to say "I know". One typed seam says it once, and both
    the MCP derivation and the REST route factory use it.
    """
    fn.__signature__ = signature
