"""Integration tests for A2A response spec compliance.

This test suite validates that:
1. A2A responses carry only spec-defined fields — no invented key like ``success``
2. Response data is identical between MCP and A2A protocols

``message`` is NOT such an invented key and is no longer asserted absent. The pin
declares it on the protocol envelope (``core/protocol-envelope.json``: "Human-readable
summary of the task result ... Generated by the protocol layer"), every response model
inherits ``adcp.types.ProtocolEnvelope``, and the implementation fills it — so it is
spec-defined payload that reaches MCP, A2A and REST alike through the one serializer,
``src/core/tools/_wire.py::to_wire``. The assertions that once demanded ``"message" not
in response_dict`` stated the opposite of the pinned envelope.

``success`` IS such an invented key, and is still asserted absent everywhere it used to
be asserted absent — plus in the places A2A used to write it. A2A derived it from
``errors`` and stamped it into every body; the pinned 3.1 tree declares a ``success``
property on three response schemas, none of them one of our fourteen tools.

The 23 curated ``__str__`` methods these tests read the buyer-facing sentence from are
deleted. The implementations write that sentence to ``message`` now, so it is graded on
the field, on a real dispatch — here for get_media_buys, and on the ``on_message_send``
pipeline output in ``tests/integration/test_a2a_skill_invocation.py``.

REPLACED, and the replacement is now COMPLETE: test_a2a_response_message_fields.py is
DELETED, not merely superseded. This header claimed to replace it while the file went on
living in the tree, and it was still being repaired -- a carrier fix landed in it during
the ecfdd7771 cleanup -- so someone was paying maintenance on tests this file had already
declared obsolete. Both of its premises were gone: ``_stamp_a2a_protocol_fields``, the
transport-side ``message`` stamp it was written against, survives nowhere in ``src/``, and
``to_wire`` is ``model_dump(mode="json")`` and nothing else, so asserting that the message
a caller set is the message that comes back asserts pydantic. Do not restore it from
history; the obligations it named are graded here and in
``tests/integration/test_a2a_skill_invocation.py`` on a real dispatch.
"""

from datetime import UTC, datetime

import pytest

from src.core.schemas import (
    CreateMediaBuySuccess,
    GetMediaBuyDeliveryResponse,
    GetProductsResponse,
    ListCreativeFormatsResponse,
    ListCreativesResponse,
    SyncCreativesResponse,
    UpdateMediaBuySuccess,
)
from tests.helpers.capture_wrapper_req import registry_impl

pytestmark = [pytest.mark.integration, pytest.mark.requires_db]


@pytest.mark.integration
class TestA2ASpecCompliance:
    """Test that A2A handlers return spec-compliant responses without extra fields.

    No case here passes ``context=``. Every one used to, and none of them asserted on
    it: ``context`` is stamped by the boundary (``_boundary._served``) and ``AdcpResponse``
    now REFUSES the keyword on construction, so a response built in a test carries none.
    ``context`` stays in each ``spec_fields`` set below -- those sets are allowlists of
    what the pin declares, compared as ``actual - spec_fields``, so a key the pin permits
    and this construction does not produce costs nothing. What the oracle can no longer
    see is a stray key riding IN on ``context``, and nothing can: the one writer is the
    boundary.
    """

    def test_get_products_spec_compliance(self):
        """Test get_products returns only spec-defined fields."""
        response_data = {
            "products": [],
            "errors": None,
        }

        # `message` is set here and nowhere else in this class: it is the field whose
        # spec-standing changed, so one case has to carry it to prove it is ADMITTED by
        # the oracle rather than merely never produced. The rest leave it unset, where
        # exclude_none drops it and the field set is unaffected either way.
        response = GetProductsResponse(**response_data, message="No products matched your requirements.")

        # Check no extra fields.
        # SDK 5.7 adds cache_scope, replayed as protocol envelope defaults; `message` is
        # the protocol envelope's own human-readable summary.
        spec_fields = {"products", "errors", "status", "context", "cache_scope", "replayed", "message"}
        response_fields = set(response.model_dump().keys())
        extra_fields = response_fields - spec_fields

        assert extra_fields == set(), f"Response has non-spec fields: {extra_fields}"
        assert response.model_dump()["message"] == "No products matched your requirements."
        assert "success" not in response_fields

    def test_sync_creatives_spec_compliance(self):
        """Test sync_creatives returns only spec-defined fields."""
        from src.core.schemas import SyncCreativeResult

        response_data = {
            "creatives": [
                SyncCreativeResult(
                    creative_id="cr-001",
                    internal_status="approved",
                    action="created",
                )
            ],
            "dry_run": False,
        }

        response = SyncCreativesResponse(**response_data)

        # Check no extra fields.
        # status and replayed are protocol-envelope defaults (GH #1710) -- same pattern as
        # GetProductsResponse/ListCreativesResponse above. `replayed` arrives on this
        # response for the same reason `message` does: every response model inherits
        # adcp.types.ProtocolEnvelope now, so the envelope's fields are on all of them.
        spec_fields = {"creatives", "dry_run", "context", "status", "replayed"}
        response_fields = set(response.model_dump().keys())
        extra_fields = response_fields - spec_fields

        assert extra_fields == set(), f"Response has non-spec fields: {extra_fields}"
        assert "success" not in response_fields

    def test_list_creatives_spec_compliance(self):
        """Test list_creatives returns only spec-defined fields."""
        from src.core.schemas import Pagination, QuerySummary

        response_data = {
            "query_summary": QuerySummary(total_matching=0, returned=0),
            "pagination": Pagination(has_more=False),
            "creatives": [],
        }

        response = ListCreativesResponse(**response_data)

        # Check no extra fields.
        # SDK 5.7 adds status, replayed as protocol envelope defaults.
        spec_fields = {
            "query_summary",
            "pagination",
            "creatives",
            "context_id",
            "format_summary",
            "status_summary",
            "context",
            "status",
            "replayed",
        }
        response_fields = set(response.model_dump().keys())
        extra_fields = response_fields - spec_fields

        assert extra_fields == set(), f"Response has non-spec fields: {extra_fields}"
        assert "success" not in response_fields

    def test_list_creative_formats_spec_compliance(self):
        """Test list_creative_formats returns only spec-defined fields."""
        response_data = {
            "formats": [],
            "creative_agents": None,
            "errors": None,
        }

        response = ListCreativeFormatsResponse(**response_data)

        # Check no extra fields.
        # SDK 5.7 adds replayed as a protocol envelope default.
        spec_fields = {"formats", "creative_agents", "errors", "status", "context", "replayed"}
        response_fields = set(response.model_dump().keys())
        extra_fields = response_fields - spec_fields

        assert extra_fields == set(), f"Response has non-spec fields: {extra_fields}"
        assert "success" not in response_fields

    def test_create_media_buy_spec_compliance(self):
        """Test create_media_buy returns only spec-defined fields.

        No ``context=``: it is stamped by the boundary (``_boundary._served``) and
        ``AdcpResponse`` refuses it on construction, and this case never asserted on it.
        ``confirmed_at``/``revision`` are passed because they carry no model default --
        they are columns the repository owns -- and neither is asserted here either.
        """
        response = CreateMediaBuySuccess.sync_success(
            media_buy_id="mb-456",
            packages=[],  # Required field per AdCP spec
            confirmed_at=datetime(2026, 1, 1, tzinfo=UTC),
            revision=1,
        )

        # Check response can be dumped (has all required fields)
        response_dict = response.model_dump()
        assert "media_buy_id" in response_dict
        assert "packages" in response_dict

        # `success` is the invented key: A2A used to stamp it into every body and AdCP
        # declares it on no response schema of our fourteen tools. `message` is NOT
        # invented -- it is the protocol envelope's declared summary -- so it is absent
        # here only because this response leaves it unset, and is not asserted absent.
        assert "success" not in response_dict

    def test_update_media_buy_spec_compliance(self):
        """Test update_media_buy returns only spec-defined fields.

        No ``context=`` and an explicit ``revision`` -- see
        ``test_create_media_buy_spec_compliance``.
        """
        response = UpdateMediaBuySuccess.sync_success(
            media_buy_id="mb-456",
            revision=1,
        )

        response_dict = response.model_dump()
        assert "media_buy_id" in response_dict

        # No invented fields (see test_create_media_buy_spec_compliance on why only this one)
        assert "success" not in response_dict

    def test_get_media_buys_spec_compliance(self):
        """get_media_buys returns only spec-defined fields.

        This oracle class is the only thing that can see a spurious wire key on this
        response: get-media-buys-response.json sets additionalProperties true, so
        schema validation accepts an invented key and says nothing.
        """
        from src.core.schemas import GetMediaBuysResponse

        response = GetMediaBuysResponse(media_buys=[])

        # `status` reaches the wire through the composed protocol-envelope branch rather
        # than the root properties. `replayed` is an SDK 5.7 envelope default the pin
        # does not declare — accepted here on the same footing as the get_products
        # case above, and legal only because this root sets additionalProperties true.
        spec_fields = {"media_buys", "errors", "status", "context", "pagination", "sandbox", "ext", "replayed"}
        extra = set(response.model_dump().keys()) - spec_fields
        assert extra == set(), f"Response has non-spec fields: {extra}"

    def test_sync_accounts_spec_compliance(self):
        """sync_accounts returns only spec-defined fields.

        Same reasoning as get_media_buys: account/sync-accounts-response.json also
        sets additionalProperties true, so a stray key passes validation unseen.
        """
        from src.core.schemas import SyncAccountsResponse

        response = SyncAccountsResponse(accounts=[])

        # `replayed` is the SDK 5.7 protocol-envelope default, accepted here on the same
        # footing as in get_media_buys above and legal only because this root sets
        # additionalProperties true.
        spec_fields = {"accounts", "errors", "status", "context", "dry_run", "sandbox", "ext", "replayed"}
        extra = set(response.model_dump().keys()) - spec_fields
        assert extra == set(), f"Response has non-spec fields: {extra}"

    def test_get_media_buy_delivery_spec_compliance(self):
        """Test get_media_buy_delivery returns only spec-defined fields."""
        from datetime import UTC, datetime

        from src.core.schemas import AggregatedTotals

        response = GetMediaBuyDeliveryResponse(
            reporting_period={
                "start": datetime.now(UTC).isoformat(),
                "end": datetime.now(UTC).isoformat(),
            },
            currency="USD",
            media_buy_deliveries=[],
            aggregated_totals=AggregatedTotals(  # Required field per AdCP spec
                spend=0.0,
                impressions=0,
                clicks=0,
                media_buy_count=0,
            ),
        )

        response_dict = response.model_dump()
        assert "media_buy_deliveries" in response_dict
        assert "reporting_period" in response_dict
        assert "currency" in response_dict
        assert "aggregated_totals" in response_dict

        # No invented fields (see test_create_media_buy_spec_compliance on why only this one)
        assert "success" not in response_dict


@pytest.mark.integration
class TestGetMediaBuysProtocolMessage:
    """``get_media_buys`` must not put a Python repr on the protocol ``message``.

    The defect this pins used to be a transport one: ``GetMediaBuysResponse`` carried no
    curated ``__str__``, so ``str(response)`` was a 316-character pydantic repr containing
    the literal ``message=None``, and both transports handed a buyer exactly that —
    ``_stamp_a2a_protocol_fields`` wrote ``str(response)`` into the A2A body, and
    ``mcp_result`` fell back to ``str(response)`` for ``ToolResult.content``.

    Both fallbacks are gone. ``message`` is a declared envelope field, the implementation
    fills it (``src/core/tools/media_buy_list.py``), and ``to_wire`` carries it out
    unchanged — so the repr can only come back by the implementation putting one there.
    That is what is graded, on the wire, for the three branches of the count form:
    zero, one, many.

    Graded through a real A2A dispatch rather than by calling the producing function:
    ``message`` reaching the body is exactly what the deleted stamp used to be
    responsible for, so a unit call on the impl would no longer see the step that
    regressed. One transport is enough because ``to_wire`` is the only body producer and
    ``test_harness_wire_response.py`` pins that the three transports agree byte for byte.
    """

    @pytest.mark.parametrize(
        ("count", "expected_message"),
        [
            (0, "No media buys found."),
            (1, "Found 1 media buy."),
            (3, "Found 3 media buys."),
        ],
    )
    def test_stamped_protocol_message_is_curated_text(self, count, expected_message, integration_db):
        """Sync on purpose: ``call_via`` bridges to ``asyncio.run()`` internally, so an
        ``async def`` test would nest event loops and swallow the RuntimeError.
        """
        from datetime import date

        from tests.factories import MediaBuyFactory, PrincipalFactory, TenantFactory
        from tests.harness.media_buy_list import MediaBuyListEnv
        from tests.harness.transport import Transport

        with MediaBuyListEnv(tenant_id="t-msg", principal_id="p-msg") as env:
            tenant = TenantFactory(tenant_id="t-msg")
            principal = PrincipalFactory(tenant=tenant, principal_id="p-msg")
            for i in range(count):
                MediaBuyFactory(
                    tenant=tenant,
                    principal=principal,
                    media_buy_id=f"mb-msg-{i}",
                    status="active",
                    start_date=date(2026, 1, 1),
                    end_date=date(2026, 12, 31),
                )
            env._commit_factory_data()
            result = env.call_via(Transport.A2A)

        body = result.wire_response
        # The row count is asserted alongside the sentence: without it a message reading
        # "No media buys found." passes on a query that silently returned nothing, which
        # is the failure the singular/plural form is least able to distinguish.
        assert len(body["media_buys"]) == count, f"expected {count} media buys on the wire, got {body['media_buys']!r}"
        assert body["message"] == expected_message


@pytest.mark.integration
class TestMCPAndA2AResponseParity:
    """Test that MCP and A2A return identical response data."""

    def test_all_response_types_declare_the_message_field(self):
        """Every AdCP response type declares ``message``, the field both protocols read.

        This replaces a ``hasattr(cls, "__str__")`` check that could not fail — every
        Python object has ``__str__`` — and whose 23 curated overrides are deleted
        anyway. The parity this class is about now rests on the field: MCP reads
        ``response.message`` for ``ToolResult.content`` and both protocols carry the
        same ``to_wire`` body, so a response type that declared no ``message`` would
        give a buyer an empty summary on one protocol and nothing on the other.
        """
        response_types = [
            CreateMediaBuySuccess,
            UpdateMediaBuySuccess,
            GetMediaBuyDeliveryResponse,
            GetProductsResponse,
            ListCreativeFormatsResponse,
            ListCreativesResponse,
            SyncCreativesResponse,
        ]

        for response_cls in response_types:
            assert "message" in response_cls.model_fields, (
                f"{response_cls.__name__} declares no `message` — it is outside the protocol "
                "envelope, so neither MCP nor A2A can give a buyer a summary of it"
            )


@pytest.mark.integration
class TestA2AResponseRegressionPrevention:
    """Prevent regressions: ensure we never add non-spec fields back."""

    def test_no_protocol_fields_in_response_data(self):
        """Ensure protocol metadata is separate from response data."""
        # Protocol fields like 'status', 'task_id', 'context_id' should be
        # in the protocol wrapper (Task), not in the response data (Artifact.parts.data)

        response = GetProductsResponse(products=[])
        response_dict = response.model_dump()

        # These are protocol-envelope fields (spec-defined on the WIRE
        # envelope's Protocol Envelope branch — see
        # tests/helpers/adcp_schema_validator.py — and populated by the protocol
        # layer at the transport boundary), correctly absent from the
        # Pydantic response MODEL itself.
        protocol_fields = {"task_id", "context_id"}  # status is actually in some AdCP responses

        violations = protocol_fields & set(response_dict.keys())
        assert violations == set(), f"Response data contains protocol fields: {violations}"


@pytest.mark.integration
class TestA2AErrorsSurviveToTheWireWithoutSuccess:
    """A2A no longer writes ``success``, and ``errors`` is what a buyer reads instead.

    This class used to pin the opposite half of the same mechanism:
    ``_stamp_a2a_protocol_fields`` DERIVED ``success`` from ``errors`` and wrote it into
    every payload, and the derivation was the thing at risk (PR #1868 found three call
    sites duplicating the stamp, one of them forcing ``success=True`` regardless of
    ``errors``).

    The stamp is deleted rather than fixed. Measured across the pinned 3.1 tree, three
    response schemas declare a ``success`` property and none of them is one of our
    fourteen tools, so A2A was writing a key AdCP does not define into every buyer's
    payload — and it had no consumers, because a buyer derives the same fact from
    ``errors``.

    That last clause is the only load this class still carries, and it is worth carrying:
    "the buyer can derive it from ``errors``" is false if ``errors`` does not reach the
    buyer. So the same dispatch now asserts the two things that replaced the derivation —
    ``errors`` arrives intact, and ``success`` does not arrive at all.
    """

    def test_get_products_populated_errors_reach_the_wire(self, integration_db):
        """Sync on purpose: ``call_a2a``/``call_via`` bridge to ``asyncio.run()``
        internally (see ``ProductEnv.call_impl``'s docstring on the same bridge) —
        an ``async def`` test would nest event loops and silently swallow the
        resulting RuntimeError.
        """
        from unittest.mock import AsyncMock

        from src.core.schemas import Error, GetProductsResponse
        from tests.bdd.steps._outcome_helpers import wire_dict
        from tests.bdd.steps.generic._dispatch import dispatch_request
        from tests.factories import PrincipalFactory, TenantFactory
        from tests.harness.product import ProductEnv
        from tests.harness.transport import Transport

        with ProductEnv(tenant_id="a2a-success-errors-test", principal_id="test_principal") as env:
            tenant = TenantFactory(tenant_id="a2a-success-errors-test")
            PrincipalFactory(tenant=tenant, principal_id="test_principal")

            # get_products has no production code path that populates
            # non-fatal errors[] today (unlike CreateMediaBuySuccess's
            # property_list_filtering advisory) — stub the tool boundary
            # A2A dispatches through, the same seam the transport is
            # contractually bound to (Pattern #5), so the serialization the
            # transport owns is graded independent of whether any business
            # path currently exercises it.
            errored_response = GetProductsResponse(
                products=[],
                errors=[Error(code="UNSUPPORTED_FEATURE", message="property_list_filtering unavailable")],
            )

            # Substituted at the REGISTRY ROW, which is what the A2A handler dispatches
            # through; a module attribute is not consulted by any transport.
            with registry_impl("get_products", AsyncMock(return_value=errored_response)):
                ctx: dict = {"env": env, "transport": Transport.A2A}
                dispatch_request(ctx, brief="display ads")

            body = wire_dict(ctx)

        assert "success" not in body, f"A2A stamped `success` back onto the payload: {body!r}"
        assert [e["code"] for e in body["errors"]] == ["UNSUPPORTED_FEATURE"], (
            f"the errors the buyer derives failure from did not reach the wire: {body!r}"
        )
